### PR TITLE
conda env improvements, testing, plot srun speedup

### PR DESCRIPTION
**Pull request by colindaven**
- modify iterable stem code in plots
- multiqc, openpyxl

### CODE REVIEW

**Comment by poer-sophia** [comment]
I tried to create a new wochenende env with your new yaml but I got this error:
solving environment: failed resolvepackagenotfound: - multiqc-1.11-pyhdfd78af_0

So I deleted the line with multiqc in the yml, created the enviroment and then installed multiqc with 
conda install -n wochenende-c bioconda -c conda-forge multiqc

Multiqc worked with this env for me. Could ou try if you can create the enviroment from this new yaml?

**Comment by colindaven** [comment]
This sounds promising, we'll have to get Ilona to try it as well. It works for me, great.

**Review by poer-sophia — APPROVED** [review]

**Comment by colindaven** [comment]
Hey, the bam.txt files are just our metagenomics file. A bam.bai (index) file belongs to every bam file. I've reverted in the next commit to dev.

**Comment by poer-sophia** [comment]
But I need the bam.txt files to get the length of the sequence for every organism. I guess it is the simplest way to get it.

**Pull request merged**
