### PR TITLE
Add 1.8, fixmates, name sorting for PE read dup calling

### PR DESCRIPTION
**Pull request by colindaven**

### CODE REVIEW

**Comment by colindaven** [comment]
@poer-sophia can you please login to github and accept the group request, thanks

**Comment by poer-sophia** [comment]
I accepted it

**Comment by colindaven** [comment]
@poer-sophia please review this - see tab "Files changed" when you get the chance and provide comments, if any. It would be good to clone the dev branch and test it if you have a few paired end -PE - test files. I have run it extensively already but always good for someone else to have a look.

Possible PE test files /working2/tmp/sophia/pe_test

**Comment by poer-sophia** [comment]
Of course, I´m gonna test it and look at it. For some reason I got the notifictaion that you mentioned me only now.

**Comment by poer-sophia** [comment]
Ich habe es bei mir mal ausprobiert, es scheint alles so funktioniert zu haben wie es soll.

**Pull request merged**
